#!/bin/sh

#Vars
apptitle="Download-OCLP"
version="1.0"
sleep 1
rm -rf /$HOME/Downloads/Download-OCLP/OpenCore-Patcher.pkg.zip
rm -rf /$HOME/Downloads/Download-OCLP/OpenCore-Patcher.pkg
mkdir -p /$HOME/Downloads/Download-OCLP
#Dialog Text
read -r -d '' applescriptCode <<'EOF'
   set dialogText to text returned of (display dialog "
Type the release number of OCLP you whant to use, the default selection is 2.4.1 Build.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The lowest you can start is ---> 1.6.0

OCLP Build available ⬇︎ 
2.4.1 - 2.4.0 - 2.3.2 - 2.3.0 
2.1.2 - 2.1.0 - 2.0.2 - 1.6.0
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
It will be downloaded in the directory Downloads/Download-OCLP

Choose a release number then click Continue

Exit Script by the Shutdown button
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" default answer "2.4.1" with icon 2 buttons {"Continue"} default button "Continue")return dialogText
EOF

dialogText=$(osascript -e "$applescriptCode");
echo " "
echo Your choice is OpenCore-Legacy-Patcher $dialogText;
echo " "
echo "Download ---> OpenCore-Legacy-Patcher $dialogText"
curl -L https://github.com/chris1111/OCLP-Dev-repos/releases/download/$dialogText/OpenCore-Patcher.pkg.zip -o $HOME/Downloads/Download-OCLP/OpenCore-Patcher.pkg.zip
Sleep 1
ditto -x -k --sequesterRsrc --rsrc $HOME/Downloads/Download-OCLP/OpenCore-Patcher.pkg.zip /$HOME/Downloads/Download-OCLP
sleep 1
rm -rf $HOME/Downloads/Download-OCLP/OpenCore-Patcher.pkg.zip
echo " "
echo "Download ---> OpenCore-Legacy-Patcher $dialogText Completed!"
Sleep 1
Open /$HOME/Downloads/Download-OCLP

osascript <<EOD
  tell application "OCLP"
      activate
  end tell
EOD
Sleep 3
echo "QUITAPP"

